@echo off
SET CLASS_FILES_TARGET_DIRECTORY=%~dp0
SET HEADER_FILES_TARGET_DIRECTORY=%~dp0\..
SET SOURCE_FILES_TARGET_DIRECTORY=%~dp0\..

"C:\Program Files\openjdk-15.0.1_windows-x64_bin\bin\javac.exe" %~dp0\*.java -d %CLASS_FILES_TARGET_DIRECTORY% -h %HEADER_FILES_TARGET_DIRECTORY% -s %SOURCE_FILES_TARGET_DIRECTORY%
