/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class explorercontextmenu_menu_ExplorerContextMenuEntry */

#ifndef _Included_explorercontextmenu_menu_ExplorerContextMenuEntry
#define _Included_explorercontextmenu_menu_ExplorerContextMenuEntry
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     explorercontextmenu_menu_ExplorerContextMenuEntry
 * Method:    executeCommand
 * Signature: (JZ)I
 */
JNIEXPORT jint JNICALL Java_explorercontextmenu_menu_ExplorerContextMenuEntry_executeCommand
  (JNIEnv *, jobject, jlong, jboolean);

#ifdef __cplusplus
}
#endif
#endif
