/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class explorercontextmenu_menu_ProcessMonitor */

#ifndef _Included_explorercontextmenu_menu_ProcessMonitor
#define _Included_explorercontextmenu_menu_ProcessMonitor
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     explorercontextmenu_menu_ProcessMonitor
 * Method:    getCurrentChildProcesses
 * Signature: ()[Lexplorercontextmenu/menu/ProcessInfo;
 */
JNIEXPORT jobjectArray JNICALL Java_explorercontextmenu_menu_ProcessMonitor_getCurrentChildProcesses
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
