/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class explorercontextmenu_menu_ExplorerContextMenu */

#ifndef _Included_explorercontextmenu_menu_ExplorerContextMenu
#define _Included_explorercontextmenu_menu_ExplorerContextMenu
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     explorercontextmenu_menu_ExplorerContextMenu
 * Method:    getEntries
 * Signature: ([Ljava/lang/String;Z[Ljava/lang/String;[Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_explorercontextmenu_menu_ExplorerContextMenu_getEntries
  (JNIEnv *, jobject, jobjectArray, jboolean, jobjectArray, jobjectArray);

/*
 * Class:     explorercontextmenu_menu_ExplorerContextMenu
 * Method:    deleteUnmanagedInstance
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_explorercontextmenu_menu_ExplorerContextMenu_deleteUnmanagedInstance
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
