/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class explorercontextmenu_menu_ExplorerContextMenuEntry */

#ifndef _Included_explorercontextmenu_menu_ExplorerContextMenuEntry
#define _Included_explorercontextmenu_menu_ExplorerContextMenuEntry
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     explorercontextmenu_menu_ExplorerContextMenuEntry
 * Method:    executeNativeCommand
 * Signature: (Z)V
 */
JNIEXPORT void JNICALL Java_explorercontextmenu_menu_ExplorerContextMenuEntry_executeNativeCommand
  (JNIEnv *, jobject, jboolean);

#ifdef __cplusplus
}
#endif
#endif
